### ISSUE TITLE
Script failed due to missing sdump

### ISSUE THREAD

**Issue by ashemedai** [zhaowenlan1779/threeSD#1]
GodMode v1.9.0
threeSD v0.2.1

After some lines that execute, I get a
```
0:/gm9/scripts/threeSDumper.gm9
line 47: build failed
sdump -w seeddb.bin
```

Looking at https://github.com/d0k3/GodMode9/releases it seems this was included from 1.7.0 onwards. And checking recent sources at https://github.com/d0k3/GodMode9/blob/760052f20de51b81c418fbbfade13f5c7032b774/arm9/source/utils/scripting.c#L115 indicates the command is still mapped. Am I missing something obvious? Sorry, rather new to the homebrew scene.

**Comment by zhaowenlan1779** [comment]
Hi there!
The `sdump` command is available in GodMode9 v1.9.0, and `build failed` actually means "command exists but failed". I recall someone else who also encountered this `build failed` issue a while ago, but most users seem to execute the script with no problems. I can't think of anything wrong in my script and you should probably report this issue to the GodMode9 team instead.

For the time being, you can just comment this line out (with `#`) so that threeSD can dump the files below it (e.g. system archives). However without seeddb you won't be able to execute some of the games imported using seed encryption.

**Comment by zhaowenlan1779** [comment]
Resolved a while ago

**Comment by ashemedai** [comment]
@zhaowenlan1779 The newer version of the script does what it should do. It does complain at the end of a missing `seeddb.bin`, indeed. Thanks.
