### ISSUE TITLE
Mac application won't boot

### ISSUE THREAD

**Issue by MuffinGamedev** [zhaowenlan1779/threeSD#13]
When I try to open the macOS release of threeSD, I just get the message, "The application "threeSD" can't be opened." I get the same error with the older releases that have a Mac port as well. I'm running macOS Mojave, version 10.14.6.

**Comment by zhaowenlan1779** [comment]
I just confirmed the releases can run on both 10.12 and 10.15.

The error you are getting might be caused by newer macOSes checking for app signature before running it.
Since threeSD does not have a signature, you'll have to override security settings and force open the app (hold Control, click on the app and select Open)
